# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["batmac"]

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["batmac"]

      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees: ["batmac"]
