run:
  build-tags:
    - crappy

linters:
  enable:
    - deadcode
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - varcheck
    - whitespace
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    # - containedctx
    - contextcheck
    # - cyclop
    - decorder
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errname
    # - errorlint
    - execinquery
    - exhaustive
    # - exhaustivestruct [deprecated]
    # - exhaustruct
    - exportloopref
    # - forbidigo
    # - forcetypeassert
    # - funlen
    # - gci
    # - gochecknoglobals
    # - gochecknoinits
    # - gocognit
    - goconst
    # - gocritic
    # - gocyclo
    # - godot
    - godox
    # - goerr113
    - gofmt
    - gofumpt
    - goheader
    # - golint [deprecated]
    # - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    # - ifshort [deprecated]
    - importas
    # - interfacer [deprecated]
    # - ireturn
    # - lll
    - maintidx
    - makezero
    # - maligned [deprecated]
    - misspell
    - nakedret
    # - nestif
    - nilerr
    - nilnil
    # - nlreturn
    # - noctx
    - nolintlint
    - nonamedreturns
    # - nosnakecase
    - nosprintfhostport
    # - paralleltest
    # - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    # - scopelint [deprecated]
    - sqlclosecheck
    - structcheck
    - stylecheck
    - tagliatelle
    - tenv
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    # - varnamelen
    - wastedassign
    # - wrapcheck
    # - wsl

issues:
  exclude-use-default: true
  exclude:
    - 'package should be `main_test` instead of `main`'
    - 'ST1018:'
    - 'Using the variable on range scope `tt` in function literal'
linter-settings:
  gofumpt:
    extra-rules: true
