---
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
builds:
  - id: build
    env:
      - CGO_ENABLED=0
    main: ./cmd/ccat
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm: ["6", "7"]
    ignore:
      - goos: windows
        goarch: arm
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -v
      - -tags=plugins,keystore
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser -X main.tags=plugins,keystore
archives:
  - name_template: "{{ .Binary }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - none*
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^update"
release:
  github:
    owner: batmac
    name: ccat
  draft: true
  prerelease: auto
  mode: append
  header: |
    ## {{ .Date }}

  footer: |

    ## NOTE
    these builds are without libcurl
signs:
  - artifacts: checksum
    args:
      - -u
      - bat@sbz.fr
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}
    output: true
brews:
  - name: ccatos
    repository:
      owner: batmac
      name: homebrew-tap
      branch: main
    description: cat on steroids.
    license: MIT
    # folder: Formula
    skip_upload: "false"
    dependencies: []
    conflicts:
      - ccat
      - ccrypt
    test: |
      system "#{bin}/ccat --version"
    install: |
      bin.install "ccat"
      (bash_completion/"ccatos").write `#{bin}/ccat --completion bash`
