repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0  # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-vcs-permalinks
      - id: end-of-file-fixer
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.8.12
    hooks:
      - id: gitleaks
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.1
    hooks:
      - id: go-fmt-import
      - id: go-vet
      # - id: go-lint
      - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      - id: go-err-check # requires github.com/kisielk/errcheck
      - id: go-static-check # install https://staticcheck.io/docs/
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        args: [--config=.golangci.yml] # optional
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 32.117.1
    hooks:
      - id: renovate-config-validator
