ci:
  skip: ["golangci-lint"]
exclude: testdata/|generated|devcontainer\.json
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-vcs-permalinks
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
        #  args: ['--no-sort-keys']
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  # - repo: https://github.com/jumanjihouse/pre-commit-hooks
  # rev: 2.1.6
  # hooks:
  # - id: forbid-binary
  # - id: markdownlint # Configure in .mdlrc
  # - id: shellcheck
  # - id: shfmt
  # - repo: https://github.com/Lucas-C/pre-commit-hooks
  # rev: v1.3.0
  # hooks:
  # - id: forbid-crlf
  # - id: remove-crlf
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
      - id: gitleaks
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: v1.0.3
    hooks:
      # - id: go-fmt-import
      # - id: go-vet
      # - id: go-lint
      # - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      # - id: go-err-check # requires github.com/kisielk/errcheck
      # - id: go-static-check # install https://staticcheck.io/docs/
      # - id: golangci-lint # requires github.com/golangci/golangci-lint
      # args: ["--allow-parallel-runners", "--go=1.17", "--config=.golangci.yml"]
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      # - id: go-generate
        # args: ["."]
      # - id: go-mod-tidy
      - id: golangci-lint # requires github.com/golangci/golangci-lint
        args:
          ["--allow-parallel-runners", "--go=1.17", "--config=.golangci.yml"]
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 35.47.0
    hooks:
      - id: renovate-config-validator
  - repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.5.1
    hooks:
      - id: check-pre-commit-ci-config
  # - repo: https://github.com/hadolint/hadolint
  # rev: v2.10.0
  # hooks:
  # - id: hadolint
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-github-workflows
      - id: check-dependabot
      - id: check-metaschema
