FROM golang:1.27-alpine@sha256:4c9fe60190a2a3350ddc51de80d0224b8a6698d12bdfc999fee45ea9d6c46dbc as build
WORKDIR /usr/src/app
# install git for go buildinfo (-B)
# hadolint ignore=DL3018
RUN apk upgrade --no-cache \
    && apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ENV CGO_ENABLED=0
# zero-install mage: version pinned by go.mod instead of @latest
# hadolint ignore=DL3062
RUN go version && go run magefiles/mage.go

# hadolint ignore=DL3006
FROM gcr.io/distroless/static-debian12@sha256:d75cdd72874d4790092fcb1b058493ecf6bb5bf2b2b897045b00ff01d91843f2
COPY --from=build /usr/src/app/ccat /usr/bin/ccat
USER 1000
ENTRYPOINT ["/usr/bin/ccat"]
