# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccatng < Formula
  desc "cat on steroids."
  homepage ""
  version "0.9.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/batmac/ccat/releases/download/v0.9.18/ccat-0.9.18-darwin-arm64.tar.gz"
      sha256 "727e8b132205e2301519d215467b186c74a53f13236652585868e19101aca203"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.18/ccat-0.9.18-darwin-amd64.tar.gz"
      sha256 "e7f47ecf72765e5f2a63fb212b95e4e352aeb476e3b0c9ab8313594c872dfbc2"

      def install
        bin.install "ccat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v0.9.18/ccat-0.9.18-linux-arm64.tar.gz"
      sha256 "9fa7c0cbce6664772342e1c204d1714f9fc7b2e4ed8dff05e80eb619ca0f0f53"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.18/ccat-0.9.18-linux-amd64.tar.gz"
      sha256 "58365cbdd1795e17b67cb26d70a8771a7b7be778d0c064f9de7e1f7707fdf096"

      def install
        bin.install "ccat"
      end
    end
  end

  conflicts_with "ccat"
end
