# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccatng < Formula
  desc "cat on steroids."
  homepage ""
  version "0.9.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/batmac/ccat/releases/download/v0.9.6/ccat-0.9.6-darwin-arm64.tar.gz"
      sha256 "bbbbe3e4aa826a636a74622c66ddabe0b35396eccf90fa748c773ee1738742e9"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.6/ccat-0.9.6-darwin-amd64.tar.gz"
      sha256 "85bc5503fdbb3fe1e4b5381025d097305e0babb66ae9bcdf6c17fa70b5c144d3"

      def install
        bin.install "ccat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/batmac/ccat/releases/download/v0.9.6/ccat-0.9.6-linux-arm64.tar.gz"
      sha256 "f76fba3ba9ea909998f75eee814a765c6fb0a9b861ff9c76408820d1e82bc7ca"

      def install
        bin.install "ccat"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/batmac/ccat/releases/download/v0.9.6/ccat-0.9.6-linux-amd64.tar.gz"
      sha256 "52b4ba95edc29767b64310c700137ea8044f618c3647019abe3b9d7421a04a31"

      def install
        bin.install "ccat"
      end
    end
  end

  conflicts_with "ccat"
end
