name: Dockerhub Description

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update hub description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: batmac
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: batmac/ccat
          short-description: ${{ github.event.repository.description }}
