name: Makefile

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
  pull_request:

jobs:
  makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3.2.0
      - run: sudo apt-get update
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Run
        run: make
