name: Makefile

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:


permissions:
  contents: read

jobs:
  makefile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: "go.mod"
          cache: true
      - run: sudo apt-get update
      - name: Install cURL Headers
        run: sudo apt-get install libcurl4-openssl-dev
      - name: Run
        run: make test
