name: Go Nancy

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  nancy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x in order to write go.list file
        uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
          cache: true
      - name: WriteGoList
        run: go list -json -m all > go.list

      - name: Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
